### ISSUE TITLE
Jenkins job is not being stopped when verigreen status is 'CANCELLED'

### ISSUE THREAD

**Issue by aleitamar** [Verigreen/verigreen#133]
Jenkins job is not being stopped when verigreen status is 'CANCELLED'

When a parent commit fails, verigreen marks the child job as CANCELLED but it is still running in jenkins.
Shouldn't verigreen stop the cancelled jenkins job in such a case?

**Comment by soninob** [comment]
which Jenkins version are you using?

**Comment by aleitamar** [comment]
@soninob 
2.89.3

**Comment by aleitamar** [comment]
@soninob FYI
Recently i setup verigreen dev env locally on my windows machine.
To bypass this issue and use java 1.8 i did the following:
1) changed spring version to `4.3.21.RELEASE` both in the root pom.xml and in the vg-common pom.xml.
2) removed `maven-javadoc-plugin` from jenkins-client pom.xml

This did not reproduce using Jenkins 2.150.1

i did not test it in production (linux docker container) yet, but locally both the hook and the collector run successfully.

**Comment by soninob** [comment]
@aleitamar did you test it on linux docker container yet?
can you supply a PR for this? I would like to merge it

**Comment by aleitamar** [comment]
@soninob 
Did not test on linux,
version 2.5.6 works fine on our linux (docker) env.
created pull request for java 1.8 support with the changes mentioned above
i'll be happy to test it if you can create a docker image for it
https://github.com/Verigreen/verigreen/pull/134

**Comment by soninob** [comment]
@aleitamar - I'm trying to test your code from forked repo, seems that I can' bypass an exception of:
java.lang.NoClassDefFoundError: org/jboss/util/xml/JBossEntityResolver.
Did you encounter this problem?
can you supply a PR without this error?

**Comment by aleitamar** [comment]
Are you using java 8?
When do you get this error? While running the server or git hook?

**Comment by soninob** [comment]
Running Jetty from verigreen-collector-webapp, using the command 

> mvn jetty:run

**Comment by ibenlays** [comment]
@soninob Works on my env using JDK 1.8

**Comment by soninob** [comment]
I'm also using JDK 1.8.
Can you share which maven version are you using?
what is you  code base, VG origin master, or alteitamar's forked? master branch or test branch?
Here is the error I'm getting:
`
INFO: Loading XML bean definitions from ServletContext resource [/WEB-INF/applic
ationContext.xml]
??? 29, 2019 8:10:00 AM org.springframework.web.context.ContextLoader initWebApp
licationContext
INFO: Root WebApplicationContext: initialization completed in 632 ms
2019-10-29 08:10:00.368:WARN:oejuc.AbstractLifeCycle:main: FAILED o.e.j.m.p.Jett
yWebAppContext@2f6bcf87{/,file:/C:/verigreen-master_aleitamar/verigreen-collecto
r-webapp/src/main/webapp/,STARTING}{file:/C:/verigreen-master_aleitamar/verigree
n-collector-webapp/src/main/webapp/}: java.lang.NoClassDefFoundError: org/jboss/
util/xml/JBossEntityResolver
java.lang.NoClassDefFoundError: org/jboss/util/xml/JBossEntityResolver
        at org.jboss.cache.config.parsing.RootElementBuilder.<clinit>(RootElemen
tBuilder.java:51)
        at org.jboss.cache.config.parsing.XmlConfigurationParser.<init>(XmlConfi
gurationParser.java:93)
        at org.jboss.cache.DefaultCacheFactory.createCache(DefaultCacheFactory.j
ava:81)
        at com.verigreen.common.jbosscache.CacheInstance.start(CacheInstance.jav
a:45)
        at com.verigreen.collector.core.ServerListener.contextInitialized(Server
Listener.java:32)
        at org.eclipse.jetty.server.handler.ContextHandler.callContextInitialize
d(ContextHandler.java:800)
`

**Comment by aleitamar** [comment]
I tested with commit id 474434c6c139f1aefd8cad7522ec5d195c13f5fa
aleitamar/master branch
eclipse version 2019-09 R (4.13.0)
Maven that comes with eclipse 3.6.1
